CREATE USER user_admin WITH PASSWORD 'ASD87912OUI';
GRANT CONNECT ON DATABASE "BigBook_db" TO user_admin;
GRANT USAGE ON SCHEMA public TO user_admin;
GRANT INSERT, UPDATE, SELECT, DELETE ON ALL TABLES IN SCHEMA public TO user_admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO user_admin;